---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{short_intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The SamplingDesignTools package provides tools for working with various study
designs in epidemiological research, specifically:

**Case-control study:**

- `draw_mcc()` to draw samples with or without matching on confounders.

**(More) extreme case-control (MECC) study:**

- `draw_mecc()` to draw MECC samples with or without matching on confounders.
- `analyse_mecc_cond()` to estimate exposure effects from MECC samples.

**Nested case-control (NCC) study:** 

- `compute_km_weights()` to compute Kaplan-Meier (KM) type weights for NCC
samples with or without the full cohort.
- `compute_km_weights_controls()` to compute KM type weights for newly collected
controls when reusing cases in a previously collected NCC sample.

**Counter-matched nested case-control study:**

- `draw_ncc_cm()` to draw counter-matched case-control samples with or without
matching on confounders.

Help documents for main functions above include minimal examples to illustrate
function usage. Please refer to the 
[online guidebook](https://nyilin.github.io/SamplingDesignTools/) 
for detailed demonstration and discussion.
